### PR TITLE
Changed dependencies to work with newest Django Release (>=3.1.3)

### PR DESCRIPTION
**Pull request by nklsw**
I modified the dependencies to work with the Django 3.1.3 **or higher** . 
With this modification the project is matching the declared requirements in the documentation:

> 
```
Requirements
* Python (3.5, 3.6, 3.7, 3.8)
* Django (3.1+)
We highly recommend and only officially support the latest patch release of each Python and Django series.
```

Since now it is **only** working with Django 3.1.3 but no newer releases which will probably lead to dependency issues in the future.

### CODE REVIEW

**Comment by nklsw** [comment]
@branks42 @eikonomega 
Is there a reason for restricting the Django version to 3.1.3 and not the latest release?

**Comment by eikonomega** [comment]
@nklsw Hello Niklas. Thanks for taking the time to share this with us. I appreciate it.

If I am remembering correctly, the `requirements.txt` file is actually only used with the test_project that is in the repo and not when you actually install the package.

HOWEVER, we are incorrectly limiting Django to 3.1.3 as you note in the `setup.py` file under the `install_requires` list. Would you mind updating that as well in this PR and then ping us?

Thanks!

**Comment by nklsw** [comment]
Yes you are right, thanks for for pointing that out @eikonomega

I have now adjusted it in the `setup.py` file.

**Comment by eikonomega** [comment]
@nklsw Thank you so much. Would you like to be added to a contributors list for this project?

**Comment by nklsw** [comment]
It was a pleasure! I like to support great projects, so I would love to be on the contributors list.

**Pull request merged**
